### ISSUE TITLE
Failed to Parse error

### ISSUE THREAD

**Issue by Lordbaane** [TelepathicGrunt/RepurposedStructures-Fabric#31] opened 2020-09-25 16:42 UTC
Getting this error upon startup, game still runs, just thought you should know.

[10:23:19] [Server thread/ERROR]: Pool element: Failed to parse repurposed_structures:worldgen/configured_feature/cobblestone_patch.json file: repurposed_structures:worldgen/configured_feature/cobblestone_patch.json; Failed to parse minecraft:worldgen/configured_feature/patch_grass_taiga.json file: minecraft:worldgen/configured_feature/patch_grass_taiga.json; Failed to parse minecraft:worldgen/configured_feature/patch_large_fern.json file: minecraft:worldgen/configured_feature/patch_large_fern.json; Failed to parse minecraft:worldgen/configured_feature/mega_pine.json file: minecraft:worldgen/configured_feature/mega_pine.json; Failed to parse minecraft:worldgen/processor_list/empty.json file: minecraft:worldgen/processor_list/empty.json; Failed to parse minecraft:worldgen/processor_list/empty.json file: minecraft:worldgen/processor_list/empty.json; Failed to parse minecraft:worldgen/processor_list/empty.json file: minecraft:worldgen/processor_list/empty.json
[10:23:19] [Server thread/ERROR]: Pool element: Failed to parse minecraft:worldgen/configured_feature/pile_hay.json file: minecraft:worldgen/configured_feature/pile_hay.json; Failed to parse repurposed_structures:worldgen/configured_feature/lily_of_the_valley.json file: repurposed_structures:worldgen/configured_feature/lily_of_the_valley.json; Failed to parse minecraft:worldgen/configured_feature/birch_bees_005.json file: minecraft:worldgen/configured_feature/birch_bees_005.json; Failed to parse minecraft:worldgen/processor_list/empty.json file: minecraft:worldgen/processor_list/empty.json
[10:23:19] [Server thread/ERROR]: Pool element: Failed to parse repurposed_structures:worldgen/configured_feature/crimson_fungi_not_planted.json file: repurposed_structures:worldgen/configured_feature/crimson_fungi_not_planted.json
[10:23:19] [Server thread/ERROR]: Pool element: Failed to parse minecraft:worldgen/configured_feature/patch_crimson_roots.json file: minecraft:worldgen/configured_feature/patch_crimson_roots.json; Failed to parse repurposed_structures:worldgen/configured_feature/crimson_fungi_not_planted.json file: repurposed_structures:worldgen/configured_feature/crimson_fungi_not_planted.json

**Comment by Lordbaane** [comment] 2020-09-25 17:00
May have something to do with Better Nether. Not sure, once I removed that mod I no longer got the coded errors.

**Comment by TelepathicGrunt** [comment] 2020-09-25 17:00
To help figure out what the issue is, I'm gonna need more information so don't worry and just ask if need help getting any of the info.

What minecraft version are you on? 
Are you using any datapack? 
What version of repurposed structures you are using? 
And may I have the full latest.log file please?

**Comment by TelepathicGrunt** [comment] 2020-09-25 17:01
Huh. I'll check out better nether and see what up later.

**Comment by Lordbaane** [comment] 2020-09-25 17:02
[2020-09-25-4.log.gz](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5284250/2020-09-25-4.log.gz)

**Comment by Lordbaane** [comment] 2020-09-25 17:03
All this started because I wanted to know what was interfering with fishing.

**Comment by Lordbaane** [comment] 2020-09-25 17:05
Version: 0.9.3+build.207
Current version of Repurposed for fabric

**Comment by TelepathicGrunt** [comment] 2020-09-25 17:06
Thank you! I'll see what I can do. Really odd it stops breaking when better nether is off. I wonder what they are doing.

**Comment by TelepathicGrunt** [comment] 2020-09-29 16:07
Another person had a similar issue but we found that it was Better Slabs crashing Repurposed Structures. Though it seems you don't have Better Slabs on. I also tried Better Nether and couldn't reproduce the crash with them on.

Are you still getting the crash? If so, can you send me your list of mods so I can quickly narrow down which is the problematic mod?

**Comment by Lordbaane** [comment] 2020-09-29 16:30
Better Slabs crashes on it's own. Had to remove it. It hasn't happened since I removed Better Nether. 
Here's an output list of the mods. I don't get the same issues now with yours and it is the latest update. 

[10:27:07] [main/INFO]: Reloading ResourceManager: Default, Clear+Glass+Pack+1.16.2.zip, mullak99s-Faithful-v1.16.4-for-MC1.16.zip, Adabranium Mod, AdaPaxels, Auto Config v1 Updated, Better Wandering Trader, BYG, CleanView, Cloth Config v4, Curios API, Economical Villager Trading, Elytra Recipe, Emerald Tools, Fabric API, Fabric API Base, Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen Handler API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric for Fabric!, Fabric Loader, Ring of Flight, GolemZ, Golems Galore, Immersive Portals Core, Immersive Portals, LibCapableData, MaLiLib, Materialisation, MC Dungeons Weapons, Mo Glass, Mod Menu, More Gems, Bookshelving, Oh, How the Crafting Has Tabled!, Mo' Structures, MounderTweaks, NBT Crafting, Ok Zoomer, Overpowered Pickles, Packed Storage, Patchouli, Pal, Project: Save the Pets!, Repurposed Structures, Respawnable Pets, Ring Of Attraction, Ring Of Growth, Rings of Ascension, Roughly Enough Items, REI (Runtime), RPGStats, Shield Disruptor, ToroHealth Damage Indicators, Trinkets, Tweakeroo, Xaero's Minimap, Xaero's World Map, Adorn, Autofish, BootZ, Caelus API, Carrier, Cave Biomes, Curio of Undying, Curious Elytra, Dawn API, Delicious Dishes, Giselbaers Durability Viewer, EquipZ, ExpandedStorage, FallingTree, GBfabrictools, Gotta Climb Fast!, Gravel Ores, Grind Enchantments, Inventory Pause, Inventory Sorter, Jankson, LibGui, Midnight Hats, Mo'Enchantments, NookBuild, Reborn Core, FleshZ, SimpleBackpack, minecraft-dungeons-pack-1-16-2-v3-0.zip, Energy, Tech Reborn, TinyTweaks, VanillaEnhanced, Ward Blocks, Wild Explorer, Faithful-1.16.2.zip, AdventureZ, Glass Doors, LambdaBetterGrass, SpruceUI

**Comment by TelepathicGrunt** [comment] 2020-09-29 16:34
Huh strange. Guess Better Nether might had patched the issue when I went to test or it was specific to just that world. I guess I'll close this report now that it isn't crashing anymore. if it does start crashing again, don't hesitate to re-open this report or make a new one. :)

**Closed by TelepathicGrunt** 2020-09-29 16:34 UTC
Labels: Mod Conflict, bug
