### ISSUE TITLE
Datapacks not overwriting loot tables

### ISSUE THREAD

**Issue by TimelapsedEon** [TelepathicGrunt/RepurposedStructures-Fabric#9] opened 2020-07-15 01:24 UTC
I have been trying to get any loot table changes to work by using a datapack and customizing them. No matter the changes, they're overwritten or not registering. Any suggestions?

**Comment by TelepathicGrunt** [comment] 2020-07-15 01:39
Do you have the datapack handy? I could take a look and see if it's formatted right.

The datapack should something like this:

Main Folder
   pack.mcmeta 
   data
       repurposed_structures
            loot_tables
                  chests
                        <the new loot table files with the same name of the one to override>

**Comment by TelepathicGrunt** [comment] 2020-07-15 01:42
Also, put the datapack in the world's datapack folder. Though resourcepack folder outside the saves folder might work too

**Comment by TimelapsedEon** [comment] 2020-07-15 02:07
I've done all of that, and even using an online JSON validator (jsonlint.com). I wish it was that simple. The datapack I'm making cross weaves treasures and recipes with other mods right now. I double checked both the structure and the spelling of all the files and folders. I'm trying to get a modded item to spawn in the end dungeons and a separate one in the end mineshafts so I can adjust the rate the players can find them. When that works out I'll adjust the non-end structure loot as well.
[ProgressiveRecipes.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4922471/ProgressiveRecipes.zip)

**Comment by TelepathicGrunt** [comment] 2020-07-15 04:01
Hmm. I just took your datapack, cut everything out except for the badlands dungeon which I changed to 
```
{
  "type": "minecraft:chest",
  "pools": [
    {
      "rolls": 10,
      "entries": [{
        "type": "minecraft:item",
        "weight": 20,
        "name": "minecraft:chain"
      }]
    }
    ]
}
```

and it seemed to have worked. I think the issue is that while the json is valid json, it's not setup right for vanilla as it is very picky. The latest.log file should have more info about which files is the problem. Can you put the end mineshaft loottable back into the chest folder, enter the world, and then post the latest.log file here? (use pastebin.com or post the actual file here).

I can read the log and it should help us figure out where the issue lies.

**Comment by TimelapsedEon** [comment] 2020-07-15 04:25
I couldn't replicate your success. Changed dungeon_badlands.json resaved the datapack, inserted it into the world Test3a: Lakes and buildings, used a command block with the command: " /setblock ~ ~1 ~ minecraft:chest{LootTable:"repurposed_structures:chests/dungeon_badlands",LootTableSeed:0} replace "(no quotes) to get me a chest with the loot from the badlands dungeon. Then when that showed no change, I teleported to the nearest badlands biome and found some dungeons and checked out their loot.
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4922876/latest.log)
![2020-07-15_00 11 43](https://user-images.githubusercontent.com/68088516/87502977-166a8c00-c631-11ea-9292-73a8483b9c82.png)
![2020-07-15_00 11 49](https://user-images.githubusercontent.com/68088516/87502979-166a8c00-c631-11ea-9d06-4325ceda6c80.png)
![2020-07-15_00 11 52](https://user-images.githubusercontent.com/68088516/87502980-17032280-c631-11ea-9a59-5177617b7ec4.png)
![2020-07-15_00 12 11](https://user-images.githubusercontent.com/68088516/87502981-17032280-c631-11ea-9872-af2b1a307584.png)
![2020-07-15_00 12 15](https://user-images.githubusercontent.com/68088516/87502982-17032280-c631-11ea-9045-fecce4fd7d6f.png)
![2020-07-15_00 12 21](https://user-images.githubusercontent.com/68088516/87502983-17032280-c631-11ea-9089-45320e21ff7a.png)
![2020-07-15_00 15 35](https://user-images.githubusercontent.com/68088516/87502984-179bb900-c631-11ea-8bb2-2e37949a6f85.png)

Screenshots in order: loot from command block. Chest 1, then 2 of first badlands dungeon. Proof of dungeon and biome it's in. Chest 1, then 2 of second badlands dungeon. Proof of dungeon and biome it's in.

Any thoughts? I'm open to considering it's on my end and user error as this is the largest datapack I've ever made. Nothing should be interfering with your loot tables from any of the other mods or datapacks since their namespace isn't considered.

**Comment by TelepathicGrunt** [comment] 2020-07-15 11:38
From the latest log file, here's the errors being thrown. It seems you might need the music disc mod on (paint) or that their item's ID is different than whats in. Or are the music discs in a different mod as paint sounds like its a painting kind of mod

```
[00:06:51] [main/WARN]: Found validation problem in {repurposed_structures:chests/dungeon_ocean}.pools[0].entries[1]->{minecraft:chests/underwater_ruin_big}.pools[2].entries[0]: Unknown loot table called paint:pcj/aquatic_discs
[00:06:51] [main/WARN]: Found validation problem in {repurposed_structures:chests/dungeon_ocean}.pools[0].entries[3]->{minecraft:chests/simple_dungeon}.pools[3].entries[0]: Unknown loot table called paint:pcj/alpha_and_beta_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/pillager_outpost}.pools[3].entries[0]: Unknown loot table called paint:pcj/beta_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/bastion_other}.pools[2].entries[0]: Unknown loot table called paint:pcj/nether_lena_raine_discs
[00:06:51] [main/WARN]: Found validation problem in {repurposed_structures:chests/dungeon_ocean}.pools[0].entries[3]->{minecraft:chests/simple_dungeon}.pools[2].entries[0]: Unknown loot table called paint:pss/staffs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/jungle_temple}.pools[1].entries[0]: Unknown loot table called paint:pcj/alpha_discs
[00:06:51] [main/WARN]: Found validation problem in {repurposed_structures:chests/dungeon_ocean}.pools[0].entries[2]->{minecraft:chests/underwater_ruin_small}.pools[2].entries[0]: Unknown loot table called paint:pcj/aquatic_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/underwater_ruin_big}.pools[2].entries[0]: Unknown loot table called paint:pcj/aquatic_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/underwater_ruin_small}.pools[2].entries[0]: Unknown loot table called paint:pcj/aquatic_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/simple_dungeon}.pools[2].entries[0]: Unknown loot table called paint:pss/staffs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/abandoned_mineshaft}.pools[2].entries[0]: Unknown loot table called paint:pcj/beta_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/woodland_mansion}.pools[4].entries[0]: Unknown loot table called paint:pcj/beta_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/bastion_bridge}.pools[4].entries[0]: Unknown loot table called paint:pcj/nether_lena_raine_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/desert_pyramid}.pools[1].entries[0]: Unknown loot table called paint:pcj/alpha_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/simple_dungeon}.pools[3].entries[0]: Unknown loot table called paint:pcj/alpha_and_beta_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/igloo_chest}.pools[2].entries[0]: Unknown loot table called paint:pcj/alpha_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/nether_bridge}.pools[1].entries[0]: Unknown loot table called paint:pcj/nether_c418_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/bastion_treasure}.pools[2].entries[0]: Unknown loot table called paint:pcj/nether_lena_raine_discs
[00:06:51] [main/WARN]: Found validation problem in {minecraft:chests/stronghold_crossing}.pools[1].entries[0]: Unknown loot table called paint:pss/staffs
```

For reference, this was the datapack that worked and replaced badlands dungeons loot with chains. I put it in the world's datapack folder and then started the game.
[ProgressiveRecipes - test.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4924868/ProgressiveRecipes.-.test.zip)

**Comment by TelepathicGrunt** [comment] 2020-07-15 12:02
Ok I did more testing. This time, I removed all other loot tables besides repurposed structures. Then I put on the flight mod. Went to create a new world and hit the datapack button. Put in the datapack. Create world. And I was able to find the winged flight core so the datapack seemed to have worked. Maybe it's the other loot tables causing the whole thing to fail? If you want, I can make a vidoe later that shows me adding the datapack to the world to make sure no step is being missed or something. idk
[ProgressiveRecipes - test2.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4924979/ProgressiveRecipes.-.test2.zip)


![image](https://user-images.githubusercontent.com/40846040/87542551-1c805d00-c671-11ea-9354-1268e3e6badb.png)

**Comment by TimelapsedEon** [comment] 2020-07-15 17:21
I'm going to investigate Paint's datapack, Paint's a username and does some large datapacks and I've already had an issue or two with them. Looks like it has modified the big and small underwater ruins tables that are referenced in your loot tables and it's got some issues with its own loot tables.
...
I haven't found the issue yet, but I *can* recreate your success in a completely blank new world with only my datapack. Looks like I get to go digging and adding one by one to see which datapack did it. Thanks for the help!

**Comment by TelepathicGrunt** [comment] 2020-07-15 22:27
Awesome! Glad you were able to find the issue. I'll close this now. :)

**Closed by TelepathicGrunt** 2020-07-15 22:27 UTC
Labels: bug
