### ISSUE TITLE
Using /locate causes huge server lag

### ISSUE THREAD

**Issue by camBrock98** [TelepathicGrunt/RepurposedStructures-Fabric#197] opened 2022-05-11 10:16 UTC
Not too sure why but after installing onto my server and trying out /locate my servers CPU usage was maxxed and everyone eventually lost connection. it happens even when looking for the vanilla structure.

**Comment by TelepathicGrunt** [comment] 2022-05-11 11:02
That sounds like your server has a mod on that broke locate or caused vanilla structures to no longer spawn. Which causes locate command to run forever and stall the server which then kicks everyone off.

Are you positive that this is even rs’s fault? As I have tested locate before and it seems fine for all structures. Can you share your modpack with me?

**Comment by camBrock98** [comment] 2022-05-11 11:14
yeah sure its something ive put together for few friends.

current mods running
- AdventureZ
- Architechtury
- Audaki cart engine
- badpackets
- cloth
- essential commands
- fabric api
- fabric tree chopper
- feature NBT deadlock be gone
- minecraft dungeons weapons and armour
- modern industrialization
- overweight farming
- repurposed structures
- roughly enough items
- world edit
- silkspawners
- wthit

Works fine on single player to be honest may be something ive done on the server

**Comment by TelepathicGrunt** [comment] 2022-05-11 11:53
What’s the world seed the server is using? I’ll give it a test later and see if I can reproduce it with those mods on

**Comment by camBrock98** [comment] 2022-05-11 11:55
i appreciate it, the seed is 6262149710291815655

**Comment by camBrock98** [comment] 2022-05-11 12:24
i just reinstalled to double check, command runs fine without RP and NBT deadlock be gone. installed and running the locate command runs forever.

**Comment by TelepathicGrunt** [comment] 2022-05-11 12:27
This is 1.18.2? It doesn’t make much sense as I don’t really touch the command and I use vanilla’s json file system to add my structures to biomes. Wondering if fabric api did something again as they had issues several times in the past with modded structures. (What version of fabric api and rs are you using?)

**Comment by TelepathicGrunt** [comment] 2022-05-11 12:29
Linking this as if this is the same issue, then this person didn’t mention that the lag spike isn’t just a few seconds but over a minute and kicks players off servers https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/196

**Comment by camBrock98** [comment] 2022-05-11 12:36
rs - 4.1.6 
api - 0.51.1

**Comment by TelepathicGrunt** [comment] 2022-05-11 22:32
just tested on a server I launched, locate seems to be working fine for me. I'm using latest fabric api, RS, etc. I made sure to show my entire mod list and the mod's versions in the picture. Is there any mod I missed or any datapack you have on as well?
![image](https://user-images.githubusercontent.com/40846040/167958174-ce3e9032-54b0-48e7-bec0-4af30e0b63ea.png)

**Comment by camBrock98** [comment] 2022-05-11 23:46
Im going to try that version of architecture, might make a difference can't see it being that though. Do I have to generate a new world when installing or can I load onto an already part generated world? Sorry its late just finished work lol. Massive thanks for the help would love to get this running in this pack

**Comment by TelepathicGrunt** [comment] 2022-05-12 00:01
You should be able to load up past worlds just fine when updating the mods.

**Comment by camBrock98** [comment] 2022-05-12 00:34
i cant thank you enough, it does seem to be working with both versions of cloth config and the older version of architecure installed. very strange! again thank you for your time these structures are awesome!

**Comment by TelepathicGrunt** [comment] 2022-05-12 00:36
Glad it is working now! Very odd tho. I’ll close this report then

**Closed as completed by TelepathicGrunt** 2022-05-12 00:36 UTC
Labels: Need more info
