### ISSUE TITLE
[1.18.2 Crash] Nether Randomizer crashing?

### ISSUE THREAD

**Issue by itsdinkd** [TelepathicGrunt/RepurposedStructures-Fabric#199] opened 2022-05-18 16:22 UTC
https://paste.corebot.dev/ihelupewuv.bash
MC: 1.18.2
RS Version: 4.1.7

Is this fixed in 4.1.8 by chance? The player who reported it to me is using a more recent, but older version of AQM2

**Comment by TelepathicGrunt** [comment] 2022-05-18 16:26
No, this looks more like the person either has a datapack or mod that blew up the structure processor json file that I use for the nether pyramid. Which then causes the pyramid to crash since the processor file was failed to be parsed by minecraft. The person will need to share their latest.log file as it might show the processor error just before world load. I also need a link to datapack to see if I can reproduce it and narrow down the offending mod/datapack that is breaking the file

**Comment by TelepathicGrunt** [comment] 2022-05-18 16:29
Actually hold up, that pyramids/nether_randomizer doesn’t exist anymore in rs. It was changed a while ago to this name and path https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/latest-released/src/main/resources/data/repurposed_structures/worldgen/processor_list/pyramids/nether.json

meaning the person has to be using a long outdated datapack. I definitely need a link to the modpack then

**Comment by BigSmoke1425** [comment] 2022-05-18 16:50
hey, im the player that reported this crash. 
Here is my latest log:
https://paste.corebot.dev/zawoteyoxi.md

**Comment by itsdinkd** [comment] 2022-05-18 16:54
> Actually hold up, that pyramids/nether_randomizer doesn’t exist anymore in rs. It was changed a while ago to this name and path https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/latest-released/src/main/resources/data/repurposed_structures/worldgen/processor_list/pyramids/nether.json
> 
> meaning the person has to be using a long outdated datapack. I definitely need a link to the modpack then

https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2

**Comment by TelepathicGrunt** [comment] 2022-05-18 22:16
@itsdinkd I downloaded AQM2 v1.2.2 - [1.18.2] and could not find any mention of repurposed_structures:pyramids/nether_randomizer in any of the files. Not even kubejs files. I launched the game and teleported to a nether pyramid and did not get any crash. Everything seems to be fine and that processor call is probably not something within your modpack unmodified.
![image](https://user-images.githubusercontent.com/40846040/169164526-8b386e56-dffb-4257-9fe1-1f932914c6e4.png)


@BigSmoke1425 Were you trying to reuse a world or upgrade a world? If so, go into that world's save folder and then into the datapack folder for that world. Look for any datapack for repurposed structures and delete them to clean slate it. Also try updating the modpack to latest version as well.

As far as I can tell, this isn't an RS issue but more of some old outdated datapack files is being used in 1.18.2 and killing the game as a result. Or maybe an old pre-1.18.2 world is trying to be reused for 1.18.2 as that might also be cause of the crash as the chunks would have the old outdated data stored in them.

**Comment by BigSmoke1425** [comment] 2022-05-19 14:35
Hey, i can't find any files in the datapack folder. should i reset the chunks from the nether? if yes, then how can i reset it? And Thanks for the help :D (I updated on the new version from the modpack too)

**Comment by TelepathicGrunt** [comment] 2022-05-19 14:37
You can delete the nether chunks to reset it yeah. Go into the world’s save folder and into the folder for the world. Then delete the DIM-1 folder as that’s the folder that hold the nether’s data. Enter the game again and the nether should be remade from scratch again and fresh

**Comment by BigSmoke1425** [comment] 2022-05-19 14:59
okay, i deleted the DIM-1. Lets hope its now working ^^

**Comment by TelepathicGrunt** [comment] 2022-05-19 20:59
@itsdinkd can you let people know that it isn’t safe to upgrade modded worlds? Got a second report linked above of someone trying to upgrade a world and getting same crash. Basically, yeah, the chunks are saved with the old processor list path for structures. 

In 1.18.2, I cleaned up my mod significantly and refactored a lot of stuff to use Mojang’s json structure system. In doing so, I also cleaned up some processor list paths. As a result, old pre-1.18.1 chunks with the rs structure may crash in 1.18.2 if they try looking for a processor list that no longer exists.

I guess a workaround can be to take the processor lists in 1.18.1 RS’s data folder, make their lists be empty [], and then shove that into a datapack or kubejs. The existence of the empty processor lists will be enough to stop the crash maybe.

**Comment by TelepathicGrunt** [comment] 2022-05-19 21:20
Sorry for the many message but @Supercow1122 and @BigSmoke1425, if you do not want to restart your worlds, try this datapack I made quickly. What it does it reintroduces the missing 1.18.1 RS processors lists that the chunks are looking for. From what I can tell, Pyramids and Witch Huts would be crashing when upgrading 1.18.1 or older RS worlds to 1.18.2 due to the refactors I did in my mod. 
[Repurposed_Structures-OldProcessors.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8734269/Repurposed_Structures-OldProcessors.zip)

However, I can't promise that the chunks won't crash due to some other outdated info. If this works, @itsdinkd this datapack might be a good idea to package with the modpack (in KubeJS or whatever) if you are expecting people to upgrade 1.18.1 or older worlds to 1.18.2

**Comment by Supercow1122** [comment] 2022-05-19 22:00
Thanks for the help! and response sorry about the repeat issue. Mustve not
seen it but i really appreciate it!

**Comment by itsdinkd** [comment] 2022-05-19 23:08
> @itsdinkd can you let people know that it isn’t safe to upgrade modded worlds? Got a second report linked above of someone trying to upgrade a world and getting same crash. Basically, yeah, the chunks are saved with the old processor list path for structures.
> 
> In 1.18.2, I cleaned up my mod significantly and refactored a lot of stuff to use Mojang’s json structure system. In doing so, I also cleaned up some processor list paths. As a result, old pre-1.18.1 chunks with the rs structure may crash in 1.18.2 if they try looking for a processor list that no longer exists.
> 
> I guess a workaround can be to take the processor lists in 1.18.1 RS’s data folder, make their lists be empty [], and then shove that into a datapack or kubejs. The existence of the empty processor lists will be enough to stop the crash maybe.

Trust me.. I have... it's also everywhere in my discord, but I believe its from people who are hosting servers thru companies and upgrading that way.

**Comment by BigSmoke1425** [comment] 2022-05-28 06:12
Thank you very much for your help

**Comment by TelepathicGrunt** [comment] 2022-05-29 00:02
closing as the datapack above resolves the issue when updating old worlds to 1.18.2.

**Closed as completed by TelepathicGrunt** 2022-05-29 00:02 UTC
Labels: bug, Cannot fix/Won’t fix
