### ISSUE TITLE
Eye of Ender doesn't work correctly

### ISSUE THREAD

**Issue by keahie** [TelepathicGrunt/RepurposedStructures-Fabric#73] opened 2021-02-04 20:23 UTC
I recently stumbled above this mod and first of all. I love it. Unfortunately the Eye of Ender Stronghold search is not working. When I throw the item, it always go to North/West. This also happens when it's the only mod installed with the default config on 1.16.4.
If I find some time I will dig into the bug myself, but can't promise anything.

**Steps to reproduce**
1. In Curseforge, create a new profile
2. Add _Repurposed Structures_ mod with the _Fabric API_ and _Jumploader_ mod to work correctly
3. Create a new World
4. Throw some Eye of Enders and follow them
5. After some time you will notice, that the eyes are only flying to North/West, even when the Stronghold is in the complete opposite direction

**Comment by TelepathicGrunt** [comment] 2021-02-04 20:55
I don't know what to say other than, it's working just fine for me. I launched Minecraft with Fabric API and latest Repurposed Structures and it lead me straight to a stronghold.
![image](https://user-images.githubusercontent.com/40846040/106953804-d2d88c00-6700-11eb-8287-6c187e7c81c4.png)

Few things, are you sure you are using only repurposed structures? And that you are using a fresh world? And that you are going past 1600 blocks from spawn? (Strongholds cannot be closer than that)

Also, make sure it isn't this Mojang bug where locate's code (which Ender Eyes use) isn't bugged and just simply pointing to a different stronghold off in the distance.

**Comment by TelepathicGrunt** [comment] 2021-02-17 22:57
Just checking in, is this still an issue even after my questions? If so, can you get me the info I ask for? It would help me narrow down the issue if it exists

**Comment by TelepathicGrunt** [comment] 2021-02-21 05:00
figure it out. It is caused by stone stores being a jerk and not having a proper category lol.  So my mod wasn't removing the stronghold properly from it but minecraft still tries to make locate find it in other biomes that cant spawn it. what the heck is this spaghetti code mojang did for strongholds lol. Fix coming soon

**Comment by TelepathicGrunt** [comment] 2021-02-21 15:02
fixed in latest release of v1.8.2!

**Closed by TelepathicGrunt** 2021-02-21 15:02 UTC
