### ISSUE TITLE
Crash at entering the Nether, Exception Ticking Player

### ISSUE THREAD

**Issue by Shlock-Konn** [TelepathicGrunt/RepurposedStructures-Fabric#23] opened 2020-08-23 18:41 UTC
Playing with Cinderscapes, Mo' Structures and Phosphor, Lithium, and Sodium. Could any of them be causing the issue?
[crash-2020-08-23_19.05.26-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5114569/crash-2020-08-23_19.05.26-server.txt)

**Comment by TelepathicGrunt** [comment] 2020-08-23 18:59
Idk why this is crashing but I think it is due to some other mod instead. I saw this as I think it is caused by a mod's bad mixin as the line that the crash report points at is here: 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/c7539853aecd6b3279410166eb5cc435d54a51e6/src/main/java/com/telepathicgrunt/repurposedstructures/world/structures/pieces/TempleNetherPools.java#L38-L41

And there's no mixin being called there on my end. You'll have to see if you can narrow down which mod is causing the crash and show them my line of code above. Maybe someone is messing with SinglePoolElement or StructurePoolBasedGenerator idk.

Also, just a heads up, the 1.16.1 version of Repurposed Structures is kind of discontinued and I'll only be focusing on 1.16.2 for now on. 

Good luck and I hope you can figure out who is causing the crash!

**Comment by Shlock-Konn** [comment] 2020-08-24 16:00
> Idk why this is crashing but I think it is due to some other mod instead. I saw this as I think it is caused by a mod's bad mixin as the line that the crash report points at is here:
> https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/c7539853aecd6b3279410166eb5cc435d54a51e6/src/main/java/com/telepathicgrunt/repurposedstructures/world/structures/pieces/TempleNetherPools.java#L38-L41
> 
> And there's no mixin being called there on my end. You'll have to see if you can narrow down which mod is causing the crash and show them my line of code above. Maybe someone is messing with SinglePoolElement or StructurePoolBasedGenerator idk.
> 
> Also, just a heads up, the 1.16.1 version of Repurposed Structures is kind of discontinued and I'll only be focusing on 1.16.2 for now on.
> 
> Good luck and I hope you can figure out who is causing the crash!

Looks like it was caused by the End: Rebellion mod. I've started [an issue thread on its author's respective GitHub page](https://github.com/EleC0TroN/ER/issues/17) and also linked this issue. Anyway, thank you for the help, I appreciate it!

**Comment by TelepathicGrunt** [comment] 2020-08-31 17:09
I'll close this issue now that they were able to fix the conflict. :)

**Closed by TelepathicGrunt** 2020-08-31 17:09 UTC
Labels: Mod Conflict, bug
