### ISSUE TITLE
C2ME Repurposed Structure fails to generate structure with default settings

### ISSUE THREAD

**Issue by Yucked** [TelepathicGrunt/RepurposedStructures-Fabric#181] opened 2022-01-29 18:27 UTC
```java
[12:55:18] [C2ME worker #1/ERROR]: 
-------------------------------------------------------------------
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:villages/oak/town_centers. Required pieces failed to generate the required amount are: [waystones:village_waystone=1]
  Make sure this structure's size in the config (if it has one) is not set too low.
  Also make sure the max height and min height for this structure in the config (if it has one) is not too close together.
  If min and max height is super close together, the structure's pieces may not be able to fit in the narrow range and spawn.
  Otherwise, if the min and max height ranges aren't close, and structure size isn't super small like 1 or 2, and this message still appears,
  please report the issue to Repurposed Structures's dev with latest.log file!
```

Related/unrelated issue: https://github.com/RelativityMC/C2ME-fabric/issues/115

**Comment by TelepathicGrunt** [comment] 2022-01-29 18:35
Is this 1.18.1? If so, RS doesn’t come with any required pieces checks for waystones. Rather, it is handled by datapacks or json files within the Waystone mods. So which Waystone mod are you trying to use and do you have any Waystone datapack? (There’s two Waystone mods on fabric)

furthermore, did you change any config for waystones?

**Comment by Yucked** [comment] 2022-01-29 19:23
This is 1.18.1.

repurposed_structures_fabric-3.3.6+1.18.1.jar
wraith-waystones-2.4.1.jar

I haven't modified any config files for both mods.

**Comment by TelepathicGrunt** [comment] 2022-01-29 20:35
Just tested with that waystone and repurposed structures. The waystones are spawning in the villages just fine with no change to config files and nothing in logs about issues spawning
![image](https://user-images.githubusercontent.com/40846040/151676762-f672cfe8-6b09-470a-91eb-8d4b9686afd4.png)

Can you share your latest.log file entirely? maybe there's an error in another json file that is killing the parsing of json files

**Comment by Yucked** [comment] 2022-01-29 21:23
I should add this is on server side
Here you go: https://mclo.gs/ROFcQBn

**Comment by LordDeatHunter** [comment] 2022-01-29 21:26
The issue might be related to MoreVillagers. It's a known incompatibility for Waystone village generation, and I'm trying to fix it for the next FW update.

**Comment by TelepathicGrunt** [comment] 2022-01-29 22:06
highly unlikely as RS uses it's own jigsaw system that no one else touches. In fact, I just put on More Villagers 3.1.1 and my Repurposed_Structures-More_Villagers_v4 datapack and both waystones and more villagers stuff are spawning just fine
![image](https://user-images.githubusercontent.com/40846040/151679022-6cdcb08d-5684-47e3-bfed-9170a206e13b.png)


The log doesn't seem to point to anything as the cause. Very odd.

**Comment by TelepathicGrunt** [comment] 2022-03-05 14:52
Im going to close this now as I am not seeing anyone else with the c2me issue over months now

**Closed as completed by TelepathicGrunt** 2022-03-05 14:52 UTC
Labels: Mod Conflict, Need more info

**Comment by zimdin12** [comment] 2025-12-18 19:27
Same issue on 1.21.10 but on fabric (this came up in google.)

**Comment by TelepathicGrunt** [comment] 2025-12-18 19:29
@zimdin12 please make a new issue report on my main repurposed structures repo with details such as the issue you see, the latest.log file, and an export of modpack or link to modpack so I can download and test

https://github.com/TelepathicGrunt/RepurposedStructures/issues
