### ISSUE TITLE
Trees Don't Float conflicts and causes Nether Temples to crash upon generation

### ISSUE THREAD

**Issue by Redd56** [TelepathicGrunt/RepurposedStructures-Fabric#36] opened 2020-10-13 07:25 UTC
https://pastebin.com/7G9eeDPV

**Comment by TelepathicGrunt** [comment] 2020-10-13 12:03
Can you delete repurposed structures configs and try again? Some people have said the issue occurred from something invalid in the configs.

After that, the next thing to try would be to test with removing some mods off as mod incompatibility is also probably causing this as well. The temple nbt files are included in the mod in the right locations and the starting pool identifier points to those files just fine. I can test later today with the mods you have on to try and reproduce the issue

**Comment by TelepathicGrunt** [comment] 2020-10-13 16:21
Ok I got the crash to occur when I downloaded most of the mods you have. However, when I went to test in my dev environment alone, all 5 of the nether temples spawn just fine. I even removed all other mods and ran repurposed structures alone and all 5 temples didnt crash. What the?

Now I gotta find which mod is breaking my temples. Or more specifically, is breaking how minecraft reads the structure pool json file from my mod. Super weird

**Comment by Redd56** [comment] 2020-10-14 03:08
okay so ima yeet that outa the pack

**Comment by Redd56** [comment] 2020-10-14 03:08
wonder why that mod does that...

**Comment by ShabanPlayz** [comment] 2020-10-16 20:05
i'm having the same issue, thanks for resolving the conflict and thereby saving me precious lifetime

**Comment by defenestrationdude** [comment] 2020-10-31 08:34
if I may add an odd footnote, running repurposed structures, trees do not float, and cinderscapes had an odd issue where looking at the upside down yellow sulfur that cinderscapes adds would crash, even if the area was (at least seemingly) otherwise safe regarding crashes; removing trees do not float resolved this, and this and cinderscapes work fine otherwise as far as I can tell. (also, I already submitted this to the cinderscapes devs, and they directed me here after reading the crash log).
[crash-2020-10-30_01.04.18-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5468778/crash-2020-10-30_01.04.18-server.txt)

**Comment by TelepathicGrunt** [comment] 2020-10-31 16:06
@defenestrationdude  That log is showing that a Nether Temple was indeed attempted to be generated meaning chunks were being loaded. And since you had Trees Don't Float on, it crashed the Nether Temple as a result. Has nothing to do with the sulfur stuff from Cinderscapes or their mod at all. Hope this helps clarify things!

**Comment by TelepathicGrunt** [comment] 2020-11-20 21:52
https://www.curseforge.com/minecraft/mc-mods/trees-do-not-float/files/3112078

Trees do not float pushed an update that fixes this mod incompatibility now! :)

**Closed by TelepathicGrunt** 2020-11-20 21:52 UTC
Labels: Mod Conflict, bug
