### ISSUE TITLE
[1.16.5] Modded dim crashes with Repurposed Structures

### ISSUE THREAD

**Issue by kwpugh** [TelepathicGrunt/RepurposedStructures-Fabric#158] opened 2021-11-28 18:03 UTC
Getting a crash inn my data pack caving  dim that uses Overworld type.

I'm not sure what might be going on.

Open issue:  https://github.com/kwpugh/mining_Dimensions-1.17/issues/15

**Comment by TelepathicGrunt** [comment] 2021-11-28 18:15
Closing cause 1.16.5 is no longer maintained and because the issue is most likely caused by Minegate lol
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/124

**Closed as completed by TelepathicGrunt** 2021-11-28 18:15 UTC
Labels: duplicate, Mod Conflict
