### ISSUE TITLE
Allure's SpeleothemBlock canPlaceAt crashes RS dungeons during worldgen

### ISSUE THREAD

**Issue by srnyx** [TelepathicGrunt/RepurposedStructures-Fabric#106] opened 2021-04-12 23:59 UTC
I was just standing still
https://paste.srnyx.xyz/ixugineyam.yaml

**Comment by TelepathicGrunt** [comment] 2021-04-13 00:26
Looks like while the dungeon was generating, Allure's Speleothem's canPlaceAt method was called and their block crashed as it isnt worldgen safe. i'll let them know about that

**Comment by TelepathicGrunt** [comment] 2021-04-13 00:27
For now while you wait, see if you can turn off their Speleothem  blocks to prevent further crashes until a fix is made

**Comment by TelepathicGrunt** [comment] 2021-04-13 00:34
Here's an issue report I made to them. Keep watch on it to know when they will release a fix. I'll close this once the issue is resolved https://www.curseforge.com/minecraft/mc-mods/allure/issues/26

**Comment by srnyx** [comment] 2021-04-13 00:57
> Here's an issue report I made to them. Keep watch on it to know when they will release a fix. I'll close this once the issue is resolved [curseforge.com/minecraft/mc-mods/allure/issues/26](https://www.curseforge.com/minecraft/mc-mods/allure/issues/26)

Sadly, I think they have gone away or like abandoned the mod.
I opened a non-related issue to this on February 28th and they haven't responded :(

**Comment by TelepathicGrunt** [comment] 2021-04-13 01:01
Dang. There's really nothing I can do on my end to resolve this. Sorry. I hope they come back soon

**Comment by TheDarkRisen** [comment] 2021-04-14 06:20
I have same issue in Craft for Exile modpack. There is Allure and RS instaled. Have any idea how turn off Speleothem?

**Comment by srnyx** [comment] 2021-04-14 11:34
> I have same issue in Craft to Exile modpack. There is Allure and RS instaled. Have any idea how turn off Speleothem?

I feel like turning it off may cause issues because they are all over cave systems.

**Comment by TelepathicGrunt** [comment] 2021-04-14 11:48
It might be possible to use mojang's worldgen system to turn off Allure's speleothems. Try this datapack. I made it quickly and couldn't test if it works. In theory, it should replace Allure's Speleothems with a new configuredfeature that does nothing.

[allure_no_spleothems.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6310568/allure_no_spleothems.zip)

**Comment by TheDarkRisen** [comment] 2021-04-14 12:56
Thank you very much! I will try it and say the results

**Comment by mahjerion** [comment] 2021-04-15 14:02
This is great. Thanks for the fix telepathic.

**Comment by mahjerion** [comment] 2021-05-11 02:31
Odd. Seems like this issue has resurfaced after updating from Repurposed 1.10.4 to 1.10.5. Could be my datapacks not loading properly so I'll double check, just wanted to post a notice in case you start getting these reports again. Worst case scenario I'll just nuke Allure in my modpack. Thanks Tele!

**Comment by TelepathicGrunt** [comment] 2021-05-11 02:37
I suspect it is the datapack not being applied as 1.10.5 RS was three small bug fixes that doesn’t impact datapacks themselves

**Comment by TelepathicGrunt** [comment] 2021-11-30 23:07
Closing this now as I am moving onto 1.18 and it seems Allure was abandoned. rip that mod.

**Closed by TelepathicGrunt** 2021-11-30 23:07 UTC
Labels: bug, Mod Conflict
