### ISSUE TITLE
[1.18] Fabric Waystones by LDH has typo in path for RS compat

### ISSUE THREAD

**Issue by ItsFooki** [TelepathicGrunt/RepurposedStructures-Fabric#165] opened 2021-12-09 09:01 UTC
Modpack currently installed Better Minecraft 1.18
Basically error there speaks for it self. Fails to load a structure. 
Keeping in mind this is on a server as well. 
-------------------------------------------------------------------
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:villages/mountains/town_centers. Required pieces failed to generate the required amount are: [waystones:stone_brick_village_waystone=1]
  Make sure this structure's size in the config (if it has one) is not set too low.
  Also make sure the max height and min height for this structure in the config (if it has one) is not too close together.
  If min and max height is super close together, the structure's pieces may not be able to fit in the narrow range and spawn.
  Otherwise, if the min and max height ranges aren't close, and structure size isn't super small like 1 or 2, and this message still appears,
  please report the issue to Repurposed Structures's dev with latest.log file!

**Comment by TelepathicGrunt** [comment] 2021-12-09 12:32
Which Waystone mod (there’s two) are you using and are you on the very latest version of said Waystone mod?

**Comment by TelepathicGrunt** [comment] 2021-12-10 02:05
It's a bug caused by Fabric Waystones by LDH due to a typo
https://github.com/LordDeatHunter/FabricWaystones/tree/master/src/main/resources/data/repurposed_structures/pool_additions/villages

Where there is mountaints, it should be mountains. They will fix it next update.

**Comment by TelepathicGrunt** [comment] 2021-12-10 02:13
if you update to v2.3.4 fabric waystones, the issue should be fixed!
https://www.curseforge.com/minecraft/mc-mods/fabric-waystones/files/3556857

**Closed as completed by TelepathicGrunt** 2021-12-10 02:13 UTC
Labels: Mod Conflict, Not caused by my mod
