### ISSUE TITLE
Major lag spikes caused by locateStructure() call on main thread when getting wandering trader recipes

### ISSUE THREAD

**Issue by Justsnoopy30** [TelepathicGrunt/RepurposedStructures-Fabric#196] opened 2022-05-10 01:12 UTC
Spark profile: https://spark.lucko.me/ygqW1hSuBq
Screenshot of repurposed structures method causing lag spike: ![image](https://user-images.githubusercontent.com/33374736/167522799-a7fc7d4a-8337-4d10-b6bd-465d90ee8db4.png)

**Comment by TelepathicGrunt** [comment] 2022-05-10 02:33
This is vanilla behavior that I can’t really change. It’s how explorer maps works. In order for them to get the structure to show on the map, they have to actually find the structure in the first place. Which is why they run the locate command under the hood and that command takes time to find a structure. Especially if it is far away.

You can reproduce the same lag with opening shipwreck’s map chest while far away from any buried treasure structure as that explorer map has to check many chunks before finding the structure. Same this here since the explorer maps I add to wandering traders tries to find mushroom village, underground bastion, or overworld cities. These structures are very rare which is why people need the maps to even find them in the first place lol. Just give the maps a few seconds to try and find the structures.

There is nothing I can do to make it any faster as this is vanilla code and it looks to be as fast as it can be from what I can tell. If some optimization mod wants to take a stab at trying to optimize the locate command, they are welcomed to try. That’s really the only solution other than using a datapack to override this file to remove my maps from wandering trader’s trades in 1.18.2 (in 1.18.1 and older, there’s a config file instead)
https://github.com/TelepathicGrunt/RepurposedStructures/blob/latest-released/src/main/resources/data/repurposed_structures/structure_map_trades/default_maps.json

Hope that clears this up. Closing this as this is normal vanilla behavior.

**Closed as completed by TelepathicGrunt** 2022-05-10 02:33 UTC
Labels: Not a bug, Cannot fix/Won’t fix

**Comment by Justsnoopy30** [comment] 2022-05-15 19:06
I see, I'm a bit surprised there isn't a mod to make this async and just update the map when the structure has been located through.

**Comment by TelepathicGrunt** [comment] 2022-06-03 22:42
Looks like bright Spark made a new mod for Forge that turns explorer map's structure locating to be async. https://www.curseforge.com/minecraft/mc-mods/async-locator

He said he may be interested in doing a fabric version. When he does so, I'll release a new RS update to use his async map code so wandering traders no longer stall the server for a few seconds. 

keep an eye on this mod!
