### ISSUE TITLE
Please use vanilla loot tables instead of replacing them with your own.

### ISSUE THREAD

**Issue by ridjack** [TelepathicGrunt/RepurposedStructures-Fabric#69] opened 2021-01-02 21:37 UTC
Replacing vanilla loot tables with your own means that any mods adding loot to vanilla tables get completely ignored. If I'm wanting to include Repurposed Structures in a modpack that includes loot-adding mods, I have to make a datapack overwriting this mod's overwrites simply to restore vanilla functionality that didn't need to be over-written in the first place.

Please use vanilla loot tables. Using your own makes my job harder, and doesn't appear to add anything.

EDIT: Along the same lines, please don't completely replace vanilla villages if you don't need to. I'm doing beta and compat testing for a mod that adds a few village buildings, and your villages don't generate any of the custom village buildings.

**Comment by TelepathicGrunt** [comment] 2021-01-02 21:53
Actually, the reason for not using vanilla lootable is to allow slight variations in loot that fits biome variants better and allow people to customize per biome variant easier. If I used the vanilla loottable (which I did in the long long past), it locks my structures in and makes it much harder for people to add loot to specific mineshafts and such. Hence why I changed it as per people's request. You can download an already made datapack of RS's loottables from here which can speed things up. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.11
Though if I recall, loottables can point to other loottables so perhaps I can make a datapack that make's rs loottables point to vanilla's instead. Which structure are you looking to have point at vanilla loottables?

And no, my mod does not touch vanilla villages at all. It uses it's own custom structures from scratch for village variants to add to biomes that vanilla villages are not in. Again, no vanilla village is replaced. You don't see the other mod's buildings in RS's villages because the mods you found do not have direct compat with RS's villages. This can be fixed with a datapack that override's RS's village house pools and just add a new entry for the other mod's building. Example pool here:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/master/src/main/resources/data/repurposed_structures/worldgen/template_pool/village/birch/houses.json

The reason each village is it's own structure is so that people can adjust village spawn rates per biome types and /locate command can find each one separately too. (doing /locate on vanilla villages to find a taiga village was hell in 1.15.2 when /locatebiome did not exist). Having separate village structures make mod compat much better as well so that mods like World Blender can easily spawn multiple villages at once in one biome. It cant do so for vanilla villages because two different ConfiguredStructures that share the same Structure base cannot spawn together in the same biome. One will always cease to exist.

I understand your frustration but I will not be reducing flexibility and functionality in my mod for very specific use cases when most people wanted the ability to adjust per biome loottables. And the village house issue would happen anyway with any other implementation of custom villages as they all rely on custom pools for houses. Any mod adding houses to village is always hardcoded to vanilla village so a datapack will need to be made for mod compat. Though if you can tell me which mod you found that their buildings are not added, I could look into making a datapack for compat that people can just quickly slap on and share the link to the datapack on my mod's page alongside the other datapacks

**Comment by ridjack** [comment] 2021-01-02 23:07
I plan to reply further after some additional discussion with better-informed colleagues, but I wanted to touch on this:

> And no, my mod does not touch vanilla villages at all [...] Again, no vanilla village is replaced.

I just spent half an hour flying around checking desert and savanna villages with the weight of the other mod's buildings increased 10x in the code. (Edited the relevant class files in IntelliJ myself and increased their weight from 5 to 50.) I checked probably twenty or so villages using this method, and I was not able to find a single instance of any of the mod's buildings.

**Comment by TelepathicGrunt** [comment] 2021-01-02 23:18
Again, I do not touch vanilla village pools at all as you can see here: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/tree/master/src/main/resources/data/repurposed_structures/worldgen/template_pool/village

And here's how I am adding my villages to biomes. I do not have any code to replace or remove vanilla villages at all.
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/cde774219531ff841fd4f4153c0c0b0413718865/src/main/java/com/telepathicgrunt/repurposedstructures/RSAddFeaturesAndStructures.java#L716-L723

To be honest, it sounds more like the mod in question is not adding their buildings to the vanilla pools safely. Are they trying to inject their building at mod startup? This could cause issues as vanilla initializes their pools by code in multiple places which can get messy. One idea could be to get the dynamic registry on world startup instead, get the structure pool registry, find all pools that has "village" and "house" in the identifier name, and then inject the mod's own piece into the pool there. That should be most compatible with all village mods although it could be too inclusive and should have a blacklist config option alongside that.

I know Waystones mod was able to add their waystone into vanilla pools and my mod's village pools successfully so they may be a good dev to ask for help with that.

**Comment by ridjack** [comment] 2021-01-02 23:20
I edited my previous comment. I'm currently suspicious that I may have another conflict whose presence was simply brought to my attention in my attempts to work with RS. I'm attempting to verify this now.

For the sake of clarity, the mods in question are Charm and Strange. I feel very confident in that particular codebase.

**Comment by ridjack** [comment] 2021-01-03 01:27
You can safely disregard my comments regarding the villages; I've confirmed there's definitely something borked in my setup that has nothing to do with RS. Please accept my apologies. 

With regards to the original loot table issue, I'm wondering if you couldn't use something like this:

`  {
    "pools": [
        {
            "rolls": 1,
            "entries": [
                {
                    "type": "minecraft:loot_table",
                    "name": "minecraft:chests/pillager_outpost",
                    "weight": 1
                }
            ]
        },
        {
            "rolls": 1,
            "entries": [
                {
                    "type": "minecraft:loot_table",
                    "name": "minecraft:chests/ruined_portal",
                    "weight": 1
                }
            ]
        }
    ]
}`

In order to preserve vanilla loot tables in appropriate structures while also allowing the desired flexibility. I've confirmed that the above JSON pulls exactly once from each table in the list; as long as the second, custom loot table is appropriately balanced, it would avoid issues of getting too much from these chests. 

Regardless, thank you for engaging with me! I hope I didn't come off too harshly.

**Comment by TelepathicGrunt** [comment] 2021-01-03 01:45
Ah. I hope you can figure out what's the issue is with the setup you got. That issue sounds very strange and Charm/Strange's code looked fine when I did a quick check. 

For the loottable stuff, the RS mineshafts actually has different foods and different material rates depending on biome variant ex: icy mineshaft has higher lapis weight, sweet berries, cookies, some ice, and slowness arrows while jungle mineshafts has glistering_melon_slice instead of golden_apple (enchanted golden apple remains), compass, shears (like miners are jungle explorers), cocoa beans instead of pumpkin seeds, etc. Some of the vanilla mineshaft loot just didn't fit the new biomes which is why I swapped some items and adjusted some rates which is why just using the vanilla loottable directly won't work for what I want. 

It's kinda funny. I guess I did a really good job at balancing the loots that they appeared very vanilla but are actually tailored quite a bit to their biomes. But it's still good you mentioned using vanilla loottables as there are some cases where that's preferred. I'll leave up this issue report until I can make a RS datapack that makes all RS structures use vanilla loottables and link it on my curseforge page and github. Probably can get it done tomorrow.

I did make a new issue report here to remind myself to make a datapack to add charm/strange houses directly to my villages. They are hardcoded to vanilla villages but I would like to eventually make a datapack that has new nbt files of their buildings that fit my village's biomes better and spawn in them. I got a lot of work cutout for me lmao

**Comment by ridjack** [comment] 2021-01-03 01:58
Thanks for looking into all that, and especially thanks for the integration stuff! I'll talk to the gal on my end who's done most of the village builds; she loves working with that stuff and might have some fun making new ones for RS biome villages. She'll probably reply here on her own if it's something she's interested in.

**Comment by ridjack** [comment] 2021-01-03 02:14
https://i.imgur.com/GSjcnW6.png

**Comment by TelepathicGrunt** [comment] 2021-01-03 15:08
Here you go! A datapack that makes all RS Structures use only the vanilla loottable of the structure they are based on. The datapack is linked on this github and on my curseforge page if you need it again later. Hope this helps! 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.12

**Closed by TelepathicGrunt** 2021-01-03 15:08 UTC

**Comment by ridjack** [comment] 2021-01-03 15:18
Thank you!
