### ISSUE TITLE
(caused by Better Slabs) Game crashes while generating villages

### ISSUE THREAD

**Issue by Kida317** [TelepathicGrunt/RepurposedStructures-Fabric#32] opened 2020-09-28 22:50 UTC
Here's crash report - 
Hope it helps! What should I do to fix it?

---- Minecraft Crash Report ----
// Don't do that.

Time: 29.09.20 0:38
Description: Exception generating new chunk

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraft.class_3785.method_16631(class_3785.java:131)
	at net.minecraft.class_3778.method_30419(class_3778.java:266)
	at com.telepathicgrunt.repurposedstructures.world.structures.VillageBaseStructure$MainStart.init(VillageBaseStructure.java:67)
	at com.telepathicgrunt.repurposedstructures.world.structures.VillageBaseStructure$MainStart.method_16655(VillageBaseStructure.java:60)
	at net.minecraft.class_3195.method_28657(class_3195.java:261)
	at net.minecraft.class_5312.method_28622(class_5312.java:35)
	at net.minecraft.class_2794.method_28508(class_2794.java:278)
	at net.minecraft.class_2794.method_16129(class_2794.java:267)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.lambda$null$18(class_3898.java:677)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.lambda$chunkGenerate$20(class_3898.java:675)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraft.class_3785.method_16631(class_3785.java:131)
	at net.minecraft.class_3778.method_30419(class_3778.java:266)
	at com.telepathicgrunt.repurposedstructures.world.structures.VillageBaseStructure$MainStart.init(VillageBaseStructure.java:67)
	at com.telepathicgrunt.repurposedstructures.world.structures.VillageBaseStructure$MainStart.method_16655(VillageBaseStructure.java:60)
	at net.minecraft.class_3195.method_28657(class_3195.java:261)
	at net.minecraft.class_5312.method_28622(class_5312.java:35)
	at net.minecraft.class_2794.method_28508(class_2794.java:278)
	at net.minecraft.class_2794.method_16129(class_2794.java:267)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: 83,-75
	Position hash: -322122547117
	Generator: net.minecraft.class_3754@6248355e
Stacktrace:
	at net.minecraft.class_3898.lambda$null$18(class_3898.java:677)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.lambda$chunkGenerate$20(class_3898.java:675)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Carobelle'/75, l='ServerLevel[chatik]', x=970.70, y=63.00, z=-927.65]]
	Chunk stats: ServerChunkCache: 4688
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,64,-176), Chunk: (at 0,4,0 in 10,-11; contains blocks 160,0,-176 to 175,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 14587 game time, 14587 day time
	Level name: chatik
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 95199 (now: false), thunder time: 90743 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:120)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 571313256 bytes (544 MB) / 1577058304 bytes (1504 MB) up to 1577058304 bytes (1504 MB)
	CPUs: 12
	JVM Flags: 10 total; -Xmn128M -Xmx1497M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		allstackable: All Stackable 1.2.4.2
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		artifice: Artifice 0.13.2+1.16.3
		autoconfig1u: Auto Config v1 Updated 3.2.2
		autofish: Autofish 0.9.0
		bambootweaks: Bamboo Tweaks unspecified
		betterslabs: Betterslabs 1.1.0
		blue_endless_jankson: jankson +
		bno: Basic Nether Ores 1.16.2-5.2.1-Fabric
		brighter: Brighter 1.0.0
		cactusleather: Cactus Leather 1.0.1
		caelus: Caelus API 0.0.9-1.16.3
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		carrier: Carrier 1.2.0
		cavebiomes: Cave Biomes 0.3.2
		chainmail: Chainmail 0.5.0
		chicken_nerf: Chicken Nerf 1.0.3+MC1.16.2-1.16.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.8
		cloth-config2: Cloth Config v4 4.8.1
		com_github_javafactorydev_lightningstorage: LightningStorage 3.1.8
		compactstatuseffects: Compact Status Effects 1.2.2
		couplings: Couplings 1.3.1
		curioofundying: Curio of Undying 1.1.0-1.16.3
		curios: Curios API 0.0.7-1.16.3
		curiouselytra: Curious Elytra 1.1.0-1.16.3
		diggusmaximus: Diggus Maximus 1.4.1-1.16.3
		dirttopath: Dirt to Path 1.3.1
		durability101: Durability101 0.0.3
		expandedconcrete: Expanded Concrete 0.0.2
		expandedstorage: ExpandedStorage 5.6.29
		fabric: Fabric API 0.22.0+build.408-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c95
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c6a7
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.8.1+f8ac1db295
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.5.1+f8ac1db295
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
		fabricloader: Fabric Loader 0.10.0+build.208
		fastgrowth: FastGrowth 1.3
		fiber: fiber 0.23.0-1
		glassdoor: Glass Doors 1.5.0-1.16
		gottaclimbfast: Gotta Climb Fast! 1.0
		gravestones: Gravestones 1.5
		healthoverlay: Health Overlay 3.6.12
		horsestatsvanilla: Horse Stats Vanilla 4.1.3
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		inventorysorter: Inventory Sorter 1.7.3-1.16
		jankson: Jankson 3.0.1+j1.2.0
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kyrptconfig: Kytpt Config 1.1.2-1.16
		leadablepandas: Leadable Pandas 1.16.2-1.0.0
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libcd: LibCapableData 3.0.2+1.16.2
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		lightoverlay: Light Overlay 5.5.3
		magna: Magna 1.4.2-1.16.2
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.3
		minihud: MiniHUD 0.19.0-dev.20200912.222204
		ml3api: ML3API 1.3.3
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.4-MC1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		morepaths: More Paths 0.0.3
		mousewheelie: Mouse Wheelie 1.5.7+mc1.16.2-pre1
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		offlineskins: OfflineSkins 1.16.3-v1-fabric
		optifabric: OptiFabric 1.6.4
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		paintingcycle: Painting Cycle 1.0.0
		pushtocraft: Push To Craft 1.0.4+mc1.16.1
		raisedclouds: Raised Clouds 1.0.0
		repurposed_structures: Repurposed Structures 1.16.3-1.6.0
		simple_backpack: SimpleBackpack 1.0.28
		sneak-through-berries: Sneak Through Berries 1.0.1
		soulbound: Soulbound 1.0.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		tinytweaks: TinyTweaks 1.0.13
		torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
		tridentfixer: Repairable Tridents 1.0.0
		tweed: Tweed API 3.0.0-beta.13
		vanilla-hammers: Vanilla Hammers 2.0.8-1.16.2
		vanilla-toolsets: Vanilla Toolsets 1.3.0
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanincoex: Vanilla Ingredients Cooking Expanded 0.1.2
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
	Player Count: 1 / 8; [class_3222['Carobelle'/75, l='ServerLevel[chatik]', x=970.70, y=63.00, z=-927.65]]
	Data Packs: vanilla (incompatible), fabric/mo_glass, fabric/simple_backpack, fabric/repurposed_structures, fabric/morepaths, fabric/fabric-tool-attribute-api-v1, fabric/curios, fabric/expandedstorage, fabric/curiouselytra, fabric/cactusleather (incompatible), fabric/libcd, fabric/expandedconcrete, fabric/vanilla-hammers, fabric/vanillaexcavators, fabric/vanincoex, fabric/tinytweaks, fabric/netheritehorsearmor, fabric/bno, fabric/curioofundying, fabric/wolveswitharmor, fabric/glassdoor, fabric/bambootweaks, fabric/vanilla-toolsets, fabric/fabric-furnaces, fabric/gravestones
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.7989
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by TelepathicGrunt** [comment] 2020-09-28 23:05
Are you using any datapack too? The crash there tends to show when the game thinks the village start pool of pieces doesn't exist even though it is shipped with my mod. If you don't have any datapack that was made to override repurposed structure's villages, then the next step is to try and delete the config files for repurposed structures. Some people said this fixes issues for some reason.

If that too doesn't work, can you put on this mod, run the game until you crash again, and then give me the latest.log file?
https://github.com/shartte/DebugWorldGenIssues/releases/tag/v1.2.0

The latest.log file from the logs folder above the mods folder will have much more information and would help me figure out which mod might be breaking the game

**Comment by Kida317** [comment] 2020-09-29 06:12
Hello! No datapacks installed. Tried to delete config - it allowed me to actually log in the world, but it crashed again 5 secs later. Put the mod you've mentioned inside and here's the log file - 
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5296771/latest.log)
Thanks for the quick answer!

**Comment by TelepathicGrunt** [comment] 2020-09-29 11:50
I noticed you are using Optifine. Optifine is known to break most worldgen mods in 1.16.2+ because of it's outdate patches and files. Can you try again but without Optifine? One big reason optifine is bad is because of this:

```
[08:08:10] [main/INFO]: [STDERR]: DynamicRegistryManager is being loaded. Further registrations pointless!
[08:08:10] [main/INFO]: [STDERR]: java.lang.Exception: Stack trace
[08:08:10] [main/INFO]: [STDERR]: 	at java.lang.Thread.dumpStack(Unknown Source)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_5455.handler$zzo000$onInit(class_5455.java:1017)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_5455.<clinit>(class_5455.java:150)
[08:08:10] [main/INFO]: [STDERR]: 	at net.optifine.util.BiomeUtils.getBiomeRegistry(BiomeUtils.java:52)
[08:08:10] [main/INFO]: [STDERR]: 	at net.optifine.util.BiomeUtils.<clinit>(BiomeUtils.java:30)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_761.method_3244(class_761.java:872)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_18097(class_310.java:1997)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_18096(class_310.java:1973)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_18099(class_310.java:1937)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1490(class_310.java:924)
[08:08:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:229)
[08:08:10] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:08:10] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:08:10] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:08:10] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:08:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
[08:08:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[08:08:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

It's loading the dynamic registry way too early which breaks pretty much most mods from registering their stuff.

**Comment by Kida317** [comment] 2020-09-29 13:58
Put out optifine - the save didn't go past loading screen,  log attached 
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5299461/latest.log)

**Comment by TelepathicGrunt** [comment] 2020-09-29 14:34
Ok now we are making progress. The registry is loaded at the right time now. But it seems someone's structure pool json is broken as the error the debugworldgen mod is showing `[15:51:12] [main/ERROR]: Error loading registry data: Not a json array:` and `[15:51:12] [main/ERROR]: Pool element: Not a json array: `

I just tested my mod and it is working for me locally. This is what I dislike about mojang's now json worldgen system lol. If someone makes a broken worldgen json, it will cause the registry to dump everything and not register anything. Since my structure's rely on the json pools I made, the game crashes when someone else's json causes the registry to lose my pools. 

Now finding which mod is gonna be really hard. I suspect it's the same mod that this person might have one too. I'll go through both modlists and start testing to find the mod
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/31

**Comment by Kida317** [comment] 2020-09-29 14:38
Wow, so cool! Thanks for your help! Can I help in any way?

**Comment by TelepathicGrunt** [comment] 2020-09-29 14:41
I'll be download and testing mods that you have one but if you really want to help, you could try making a new world, do /locate repurposed_structures:swamp_village, teleport to it and get the crash. Then start removing half of the mods on and enter the world to see if the crash still happens. Then take the half of mods that crashes the game and cut them in half again and test that. Keep cutting the number of mods in half and it'll narrow down to the mod that conflicts with mine. That's what I am going to be doing myself  too

**Comment by Kida317** [comment] 2020-09-29 14:44
k, i have a spare minute so gonna do that rn, ttyl

**Comment by Kida317** [comment] 2020-09-29 15:03
Well, I made a new world and did what you've told (The string is actually /locate repurposed_structures:village_swamp x-D) and it didnt't crash? I hopped around to other types (birch is sooo pretty!!) but it didn't seem to matter. Optifine was in there, I didn't delete anything. Weird. Here's the log
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5299996/latest.log)

**Comment by TelepathicGrunt** [comment] 2020-09-29 15:09
So it's only crashing in that one world? what the...
The log still shows it's having issues with a json entry `[15:51:12] [main/ERROR]: Pool element: Not a json array:`

I tested these mods so far and no issues appeared yet. 
couplings@1.3.1,  
torohealth@1.16.3-fabric-1, 
structurized@1.1.0, 
mo_glass@1.4-MC1.16.3, 
simple_backpack@1.0.28, 
expandedstorage@5.6.29, 
golemsgalore@0.2.0+mc.1.16.2, 
cavebiomes@0.3.2, 
tinytweaks@1.0.13,

**Comment by Kida317** [comment] 2020-09-29 15:12
No, it crashed before in a different world even before spawning me in from the log i could see it was because i spawned right beside a village. I dont have that world anymore tho, sorry

**Comment by Kida317** [comment] 2020-09-29 15:18
although i think its those log reports - i tried to load it... Dunno if it helps
[2020-09-28-2.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5300086/2020-09-28-2.log)
[2020-09-28-3.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5300088/2020-09-28-3.log)
[2020-09-28-4.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5300090/2020-09-28-4.log)

**Comment by Kida317** [comment] 2020-09-29 15:26
Also dunno why i didnt think about it before - here is my mod folder, so you dont have to download EVERYTHING manually
[M1.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5300141/M1.zip)
[M2.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5300149/M2.zip)

**Comment by TelepathicGrunt** [comment] 2020-09-29 15:33
Thank you! I was able to reproduce the issue. Something is killing the Jungle Village (which is the one village you didn't teleport to).

Gonna try and figure out who it is messing with it

**Comment by TelepathicGrunt** [comment] 2020-09-29 16:05
Found it. It's Better Slabs. Not sure why they crash my mod but I suspect they change how some block properties are set and cuases minecraft to die when parsing json with slabs? Oof. 

You can removed Better Slabs or Repurposed Structures (after making sure you have the latest fabric API) until Better Slabs can figure out how to fix the issue.

Thank you for being patient with me!

**Comment by Kida317** [comment] 2020-09-29 16:06
thanks for your help! great job!

**Comment by TelepathicGrunt** [comment] 2020-10-04 20:20
https://www.curseforge.com/minecraft/mc-mods/better-slabs/files/3071998

They just released a fix so I'll close this issue now. :)

**Closed by TelepathicGrunt** 2020-10-04 20:20 UTC
Labels: Another mod's issue, bug
