### ISSUE TITLE
1.16.2 Server Crash - RSIglooPieces$Piece.method_14931

### ISSUE THREAD

**Issue by Katorone** [TelepathicGrunt/RepurposedStructures-Fabric#21] opened 2020-08-16 00:20 UTC
https://pastebin.com/WVXG98p1

**Comment by TelepathicGrunt** [comment] 2020-08-16 02:13
This is actually a crash caused by Gunpower mod. You can remove Gunpower Sleepvote mod until they push a bugfix for the base gunpowder mod. I have a bug report already made to them here that you can watch to know when the crash fix is released. :)
https://github.com/Gunpowder-MC/GunpowderSleepVote/issues/1

**Comment by martmists** [comment] 2020-08-16 02:59
Fixed by us, can be closed.

**Comment by TelepathicGrunt** [comment] 2020-08-16 03:02
Nice! Marking as resolved

**Closed by TelepathicGrunt** 2020-08-16 03:02 UTC
Labels: Mod Conflict, bug

**Comment by Katorone** [comment] 2020-08-16 03:08
Thanks !
