### ISSUE TITLE
Feature placement NPE crash

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/RepurposedStructures-Fabric#179] opened 2022-01-23 05:40 UTC
[crash report](https://bpa.st/SYPA)

I was in the Nether. LMK if there's any other info you need not already in the crash report.

**Comment by B00MxHartShotx** [comment] 2022-01-23 05:49
https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone
https://www.curseforge.com/minecraft/mc-mods/no-null-processors
do you have both of these?
i just came to make sure i closed my ticket about a similar issue and these fixed it

**Comment by supersaiyansubtlety** [comment] 2022-01-23 05:51
yeah, I do

the current version of the mod won't let the game launch if you don't have them (at least for no_null_processors)

**Comment by B00MxHartShotx** [comment] 2022-01-23 05:52
copy that. telepathicgrunt was quick and knew the answer when i reached out. do be safe!

**Comment by TelepathicGrunt** [comment] 2022-01-23 12:40
is this constantly happening in one place in the nether? Like was it a one time thing or is it stopping you from going a certain spot in the nether?

**Comment by TelepathicGrunt** [comment] 2022-01-23 14:47
If the issue is still persistent, try v3.3.4. The weird thing is the code it is saying it having a null crash is literally impossible for it to get null. So that's spooky. I tried something in v3.3.4 to see if it could solve it

https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/commit/b205e2707d21ceeb6c0fb3cf0bd4279ba6878a83

**Comment by supersaiyansubtlety** [comment] 2022-01-23 23:39
It only happened once, seemingly randomly, so unfortunately I can't effectively check if it's been fixed. 

Some details:
- the overworld is a void world
- I'd only moved around a few chunks in the nether
- I'd entered and left the nether and saved+quit without issue before the crash
- I was in creative
- I flew around in new chunks a bit when trying to reproduce the crash

**Comment by TelepathicGrunt** [comment] 2022-01-24 22:37
I think I'll close this now as I switched the map to be a ConcurrentHashMap and I am using computeIfAbsent so there should not be any concurrency issue or null values being thrown around for sure. Hopefully this was just a one time thing

**Closed as completed by TelepathicGrunt** 2022-01-24 22:37 UTC
Labels: bug
