### ISSUE TITLE
Crash at boot with 2.1.4

### ISSUE THREAD

**Issue by AndreiTS** [TelepathicGrunt/RepurposedStructures-Fabric#130] opened 2021-07-25 14:28 UTC
https://paste.ee/p/vE5Sp

**Comment by TelepathicGrunt** [comment] 2021-07-25 14:59
Can you quickly test this jar and see if this works? I believe the issue is I didn't mark my modifyconstant mixin as not required so that it could gracefully fail if another mod mixins the same spot (modifyconstant mixins cannot modify the same thing or else they crash if one of the mixins is marked as required)

**Comment by TelepathicGrunt** [comment] 2021-07-25 14:59
Sorry, here's the correct jar i would like you to test please
[repurposed_structures_fabric-2.1.5b+1.17.1.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6874073/repurposed_structures_fabric-2.1.5b%2B1.17.1.zip)

**Comment by AndreiTS** [comment] 2021-07-25 15:26
Same crash: https://paste.ee/p/k65wL

**Comment by TelepathicGrunt** [comment] 2021-07-25 16:06
shoot. I think I hit a weird edge case limitation of mixins. I'm asking around for how to properly fix it but if no solution comes up, I think I know how to do a hacky workaround.

**Comment by TelepathicGrunt** [comment] 2021-07-25 16:29
just released v2.1.5 that fixes the issue for good. You can grab the fixed jar from curseforge when it is approved!

**Closed as completed by TelepathicGrunt** 2021-07-25 16:29 UTC
Labels: bug
